name: Deploy Frontend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nosecomo/front-despachos-innovatech:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull nosecomo/front-despachos-innovatech:latest
            docker stop frontend-despachos || true
            docker rm frontend-despachos || true
            docker run -d \
              --name frontend-despachos \
              -p 80:80 \
              nosecomo/front-despachos-innovatech:latest